### ISSUE TITLE
关于其他通道的通知模块

### ISSUE THREAD

**Issue by davidelectricfree** [scjtqs2/mtlogin#1]
大佬，由于是go的，我不是很熟悉，想请教一下
1. 目前的通知我看了下代码，用的是您私有的token，好像没办法使用通知功能，后面有可能用类似企业微信这种吗
3. 然后除了通知功能，目前我是用docker部署了，好像到了时间日志里面也没执行，不知道为什么，5 19 * * * 修改成这个了，是19:02分修改的，19:05分似乎没有执行，添加了auth和ua，![image](https://github.com/user-attachments/assets/2f989a13-a26b-4ab6-a196-ea18ddf42b2f)

**Comment by davidelectricfree** [comment]
好像有日志了，显示checkToken，但是auth我已经填上去了呀，是填得不对吗

**Comment by davidelectricfree** [comment]
![image](https://github.com/user-attachments/assets/1accf23e-544f-4b56-b28d-6d9d08593a65)

**Comment by davidelectricfree** [comment]
![image](https://github.com/user-attachments/assets/5881cd1b-76c2-49ac-8520-a7a0a35dc248)
选的这个地方的，是不对吗

**Comment by scjtqs2** [comment]
> ![image](https://private-user-images.githubusercontent.com/36690822/393591289-5881cd1b-76c2-49ac-8520-a7a0a35dc248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDk3MjIsIm5iZiI6MTczMzcwOTQyMiwicGF0aCI6Ii8zNjY5MDgyMi8zOTM1OTEyODktNTg4MWNkMWItNzZjMi00OWFjLTg1MjAtYTdhMGEzNWRjMjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxNTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZDMwMGYzYmU2YzQ0YmQ2NmY3ZDNkODQ5ZWFmMGM5MDQ1OGIxYzA5ZWI3MGI1YmQ1YjhiNmYyODkyZWQ2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._fkiPeFX8t9n2vkHwDXdCf5RE7KC87rlfJU-csYtOrc) 选的这个地方的，是不对吗

@davidelectricfree auth确实是这个，没问题。

**Comment by scjtqs2** [comment]
> ![image](https://private-user-images.githubusercontent.com/36690822/393591230-1accf23e-544f-4b56-b28d-6d9d08593a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDk3MjIsIm5iZiI6MTczMzcwOTQyMiwicGF0aCI6Ii8zNjY5MDgyMi8zOTM1OTEyMzAtMWFjY2YyM2UtNTQ0Zi00YjU2LWIyOGQtNmQ5ZDA4NTkzYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxNTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MWJjNzIzNGZhZTE4ZDM5YzBiMjIwZDE1NjVmOTk4ZjAyMmM1ZDBmOGNlMTJhY2E4MTAzZThmNmM5OGM3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4nMm3rXZPOj1ibP44Ck_PWnmg6XlkzJ9BLyNr7JRXgs)

api接口请求超时了。确认下你的账号的api地址是不是api.m-team.io。地址可以在你抓auth的地方找请求地址。如果地址和默认预制的不一样，需要你自己通过环境变量添加进去。

**Comment by davidelectricfree** [comment]
> > ![image](https://private-user-images.githubusercontent.com/36690822/393591230-1accf23e-544f-4b56-b28d-6d9d08593a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDk3MjIsIm5iZiI6MTczMzcwOTQyMiwicGF0aCI6Ii8zNjY5MDgyMi8zOTM1OTEyMzAtMWFjY2YyM2UtNTQ0Zi00YjU2LWIyOGQtNmQ5ZDA4NTkzYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxNTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MWJjNzIzNGZhZTE4ZDM5YzBiMjIwZDE1NjVmOTk4ZjAyMmM1ZDBmOGNlMTJhY2E4MTAzZThmNmM5OGM3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4nMm3rXZPOj1ibP44Ck_PWnmg6XlkzJ9BLyNr7JRXgs)
> 
> api接口请求超时了。确认下你的账号的api地址是不是api.m-team.io。地址可以在你抓auth的地方找请求地址。如果地址和默认预制的不一样，需要你自己通过环境变量添加进去。

我又研究了下，我登录的地址是https://zp.m-team.io/，研究了下代码里面的是https://kp.m-team.cc/index，这个不同，导致登录失效，我通过后面这个地址登录就好了

**Comment by scjtqs2** [comment]
> 大佬，由于是go的，我不是很熟悉，想请教一下
> 
> 1. 目前的通知我看了下代码，用的是您私有的token，好像没办法使用通知功能，后面有可能用类似企业微信这种吗
> 2. 然后除了通知功能，目前我是用docker部署了，好像到了时间日志里面也没执行，不知道为什么，5 19 * * * 修改成这个了，是19:02分修改的，19:05分似乎没有执行，添加了auth和ua，![image](https://private-user-images.githubusercontent.com/36690822/393590617-2f989a13-a26b-4ab6-a196-ea18ddf42b2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDk4OTAsIm5iZiI6MTczMzcwOTU5MCwicGF0aCI6Ii8zNjY5MDgyMi8zOTM1OTA2MTctMmY5ODlhMTMtYTI2Yi00YWI2LWExOTYtZWExOGRkZjQyYjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxNTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOGRlMzdkZGYzZjAzNWM3MzVkZDZiMGU1MDI3NjQ2NWEwMjQ0NGU4YWRjMWU3OTk3N2U1YzY1ODBlYzUwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cXzt6T5pm_sZe4Mp5DXLxqWhtVOXXhOE1h-OH8IU5n8)

第一次使用，定时任务建议设置成 * * * * * 每分钟触发来调试。通过日志来确保能成功。

其他推送的，后面有空再说吧（当然，你有时间也可以pr进来）。现在的推送可以在这里面`https://wx.scjtqs.com/qq/user/bind`这里面自行注册token。目前是通过qq的方式推送。

**Comment by davidelectricfree** [comment]
> > 大佬，由于是go的，我不是很熟悉，想请教一下
> > 
> > 1. 目前的通知我看了下代码，用的是您私有的token，好像没办法使用通知功能，后面有可能用类似企业微信这种吗
> > 2. 然后除了通知功能，目前我是用docker部署了，好像到了时间日志里面也没执行，不知道为什么，5 19 * * * 修改成这个了，是19:02分修改的，19:05分似乎没有执行，添加了auth和ua，![image](https://private-user-images.githubusercontent.com/36690822/393590617-2f989a13-a26b-4ab6-a196-ea18ddf42b2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDk4OTAsIm5iZiI6MTczMzcwOTU5MCwicGF0aCI6Ii8zNjY5MDgyMi8zOTM1OTA2MTctMmY5ODlhMTMtYTI2Yi00YWI2LWExOTYtZWExOGRkZjQyYjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxNTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOGRlMzdkZGYzZjAzNWM3MzVkZDZiMGU1MDI3NjQ2NWEwMjQ0NGU4YWRjMWU3OTk3N2U1YzY1ODBlYzUwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cXzt6T5pm_sZe4Mp5DXLxqWhtVOXXhOE1h-OH8IU5n8)
> 
> 第一次使用，定时任务建议设置成 * * * * * 每分钟触发来调试。通过日志来确保能成功。成功后再调整成你喜欢的定时
> 
> 其他推送的，后面有空再说吧（当然，你有时间也可以pr进来）。现在的推送可以在这里面`https://wx.scjtqs.com/qq/user/bind`这里面自行注册token。目前是通过qq的方式推送。

好的，我研究下，主要是go确实不咋熟悉，谢谢，有时间我看看咋弄，十分感谢

**Comment by davidelectricfree** [comment]
#2
