### ISSUE TITLE
始终显示cookie有问题

### ISSUE THREAD

**Issue by davidelectricfree** [scjtqs2/mtlogin#5]
账号密码，secret包括auth都填了啊，要用代理吗？奇怪，用的auth是有效的，浏览器同样的auth，秒登，不用密码账号。而且同样的ip环境。
![Screenshot_2024-12-10-08-34-52-79_e39d2c7de19156b0683cd93e8735f348.jpg](https://github.com/user-attachments/assets/0cb73eaa-845f-44d8-8560-e459aee4605f)

![Screenshot_2024-12-10-08-37-03-31_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/user-attachments/assets/50cf1f1d-dc27-48bb-9772-38a20459b7bb)

**Comment by scjtqs2** [comment]
> 账号密码，secret包括auth都填了啊，要用代理吗？奇怪，用的auth是有效的，浏览器同样的auth，秒登，不用密码账号。而且同样的ip环境。 ![Screenshot_2024-12-10-08-34-52-79_e39d2c7de19156b0683cd93e8735f348.jpg](https://private-user-images.githubusercontent.com/36690822/394058397-0cb73eaa-845f-44d8-8560-e459aee4605f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3OTkyMzgsIm5iZiI6MTczMzc5ODkzOCwicGF0aCI6Ii8zNjY5MDgyMi8zOTQwNTgzOTctMGNiNzNlYWEtODQ1Zi00NGQ4LTg1NjAtZTQ1OWFlZTQ2MDVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDAyNDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkM2I0ZGIzNDk4Y2YwNmQ3NjhlMjM2NjRhOGM0YTUzOWRlNjcyZmE2NDlkZjg1NjZjMWYzNDNhMGYxNmQwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mk8E6tuWmSTgEF4pI2ZtmOihnQeeUPhTAQ925LJhEWU)
> 
> ![Screenshot_2024-12-10-08-37-03-31_df198e732186825c8df26e3c5a10d7cd.jpg](https://private-user-images.githubusercontent.com/36690822/394059190-50cf1f1d-dc27-48bb-9772-38a20459b7bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3OTkyMzgsIm5iZiI6MTczMzc5ODkzOCwicGF0aCI6Ii8zNjY5MDgyMi8zOTQwNTkxOTAtNTBjZjFmMWQtZGMyNy00OGJiLTk3NzItMzhhMjA0NTliN2JiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDAyNDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNjZhMDhiYjUxMDMwZjM0YjE2NWU5YmZiNTVlYjk1OTRkNWVjM2EyZTMyODkwZTNhZmVlNmVjM2VmOTJmNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vMYa0pptFBVm6S0AWvJZQXg0vgdky6X-RpC7LKACZaY)

你这个API_HOST 填`https://api.m-team.cc`，
API_REFERER填`https://zp.m-team.io/index` 试试。

**Comment by scjtqs2** [comment]
@davidelectricfree 我去https://zp.m-team.io看了看。
API_HOST和API_REFERER都和默认的不一样。需要手动指定
API_HOST：`"https://api.m-team.cc"`
API_REFERER: `"https://zp.m-team.io/"`
密码登录，你也可以用默认的API_HOST和API_REFERER，也就是不填。

**Comment by davidelectricfree** [comment]
> @davidelectricfree 我去https://zp.m-team.io看了看。
> API_HOST和API_REFERER都和默认的不一样。需要手动指定
> API_HOST：`"https://api.m-team.cc"`
> API_REFERER: `"https://zp.m-team.io/"`
> 密码登录，你也可以用默认的API_HOST和API_REFERER，也就是不填。
> 

好的，我试试

**Comment by davidelectricfree** [comment]
> @davidelectricfree 我去[https://zp.m-team.io看了看。](https://zp.m-team.io%E7%9C%8B%E4%BA%86%E7%9C%8B%E3%80%82) API_HOST和API_REFERER都和默认的不一样。需要手动指定 API_HOST：`"https://api.m-team.cc"` API_REFERER: `"https://zp.m-team.io/"` 密码登录，你也可以用默认的API_HOST和API_REFERER，也就是不填。

API_HOST：api.m-team.cc  可以，程序里面会自动添加https：，谢谢，现在可以了，然后我打算添加一个计划时间的随机值，到时候添加PR。
另外， 除了随机时间外，我还有两个新的想法：
1. 我注意到反馈回来的log日志里面好像有 lastlogin 和 lastbrose 的时间值，发现这个值好像没有随着脚本的使用而更新，这个站点的多少天不登录和上面这两个数值有关系吗
2. 有兴趣把魔力值，上传值，下载值提取出来，做到反馈信息里面吗

**Comment by scjtqs2** [comment]
> > @davidelectricfree 我去[https://zp.m-team.io看了看。](https://zp.m-team.io%E7%9C%8B%E4%BA%86%E7%9C%8B%E3%80%82) API_HOST和API_REFERER都和默认的不一样。需要手动指定 API_HOST：`"https://api.m-team.cc"` API_REFERER: `"https://zp.m-team.io/"` 密码登录，你也可以用默认的API_HOST和API_REFERER，也就是不填。
> 
> API_HOST：api.m-team.cc 可以，程序里面会自动添加https：，谢谢，现在可以了，然后我打算添加一个计划时间的随机值，到时候添加PR。 另外， 除了随机时间外，我还有两个新的想法：
> 
> 1. 我注意到反馈回来的log日志里面好像有 lastlogin 和 lastbrose 的时间值，发现这个值好像没有随着脚本的使用而更新，这个站点的多少天不登录和上面这两个数值有关系吗
> 2. 有兴趣把魔力值，上传值，下载值提取出来，做到反馈信息里面吗

魔力值那些信息，api/member/profile接口的返回里面就有。
 lastlogin 是登录的时间，要重新登录才会更新，一般auth可以管1个月。lastbrose倒是没注意过。
![image](https://github.com/user-attachments/assets/2682e8d2-4838-4366-a834-f8388f7450d0)
在这我是确认了时间刷新了的。

**Comment by davidelectricfree** [comment]
> > > @davidelectricfree 我去[https://zp.m-team.io看了看。](https://zp.m-team.io%E7%9C%8B%E4%BA%86%E7%9C%8B%E3%80%82) API_HOST和API_REFERER都和默认的不一样。需要手动指定 API_HOST：`"https://api.m-team.cc"` API_REFERER: `"https://zp.m-team.io/"` 密码登录，你也可以用默认的API_HOST和API_REFERER，也就是不填。
> > 
> > 
> > API_HOST：api.m-team.cc 可以，程序里面会自动添加https：，谢谢，现在可以了，然后我打算添加一个计划时间的随机值，到时候添加PR。 另外， 除了随机时间外，我还有两个新的想法：
> > 
> > 1. 我注意到反馈回来的log日志里面好像有 lastlogin 和 lastbrose 的时间值，发现这个值好像没有随着脚本的使用而更新，这个站点的多少天不登录和上面这两个数值有关系吗
> > 2. 有兴趣把魔力值，上传值，下载值提取出来，做到反馈信息里面吗
> 
> 魔力值那些信息，api/member/profile接口的返回里面就有。 lastlogin 是登录的时间，要重新登录才会更新，一般auth可以管1个月。lastbrose倒是没注意过。 ![image](https://private-user-images.githubusercontent.com/86882590/394138273-2682e8d2-4838-4366-a834-f8388f7450d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTA0NzAsIm5iZiI6MTczMzgxMDE3MCwicGF0aCI6Ii84Njg4MjU5MC8zOTQxMzgyNzMtMjY4MmU4ZDItNDgzOC00MzY2LWE4MzQtZjgzODhmNzQ1MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA1NTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NmM2ZjllMzk4N2JhMWI2ZjA2M2NmMTQ3OTA2YjUwMzQ2OGYzYzU2YzVmZWEyN2FiYzkyM2E0NTU5OGNjZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ed2INum6FyKcR-9vVfarlxP_ipsI0HgDgkoMCulwcGM) 在这我是确认了时间刷新了的。

嗷嗷，确实如此，我也看到了。
对，我看到日志里面已经有上传值、魔力值和下载值这些信息了，我在想看要不要把他做到推送里面，这样知道自己当前上传量是多少就有数了。
后面为了避免过于规律的登录信息，那个随机的功能我来弄。

**Comment by davidelectricfree** [comment]
#6

**Comment by davidelectricfree** [comment]
> > > @davidelectricfree 我去[https://zp.m-team.io看了看。](https://zp.m-team.io%E7%9C%8B%E4%BA%86%E7%9C%8B%E3%80%82) API_HOST和API_REFERER都和默认的不一样。需要手动指定 API_HOST：`"https://api.m-team.cc"` API_REFERER: `"https://zp.m-team.io/"` 密码登录，你也可以用默认的API_HOST和API_REFERER，也就是不填。
> > 
> > 
> > API_HOST：api.m-team.cc 可以，程序里面会自动添加https：，谢谢，现在可以了，然后我打算添加一个计划时间的随机值，到时候添加PR。 另外， 除了随机时间外，我还有两个新的想法：
> > 
> > 1. 我注意到反馈回来的log日志里面好像有 lastlogin 和 lastbrose 的时间值，发现这个值好像没有随着脚本的使用而更新，这个站点的多少天不登录和上面这两个数值有关系吗
> > 2. 有兴趣把魔力值，上传值，下载值提取出来，做到反馈信息里面吗
> 
> 魔力值那些信息，api/member/profile接口的返回里面就有。 lastlogin 是登录的时间，要重新登录才会更新，一般auth可以管1个月。lastbrose倒是没注意过。 ![image](https://private-user-images.githubusercontent.com/86882590/394138273-2682e8d2-4838-4366-a834-f8388f7450d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTkyMzIsIm5iZiI6MTczMzgxODkzMiwicGF0aCI6Ii84Njg4MjU5MC8zOTQxMzgyNzMtMjY4MmU4ZDItNDgzOC00MzY2LWE4MzQtZjgzODhmNzQ1MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYzNiYTNkNDcyYjhkM2E2ZGE1NDljOWE3NDkxNDFkNzlhNmNjYzM3YzcwNjEwZmU3OTNjOWU1MjhiMDY5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vVZiflf1c2VNvPoA2gmV7iMTs0PgAEEz8ZRDPxhf8PA) 在这我是确认了时间刷新了的。

#6

**Comment by scjtqs2** [comment]
> 1. lastlogin 和 lastbrose 的时间值

@davidelectricfree  lastlogin 和 lastbrose 的时间值的问题修复了。更新docker镜像就行

**Comment by davidelectricfree** [comment]
> > 1. lastlogin 和 lastbrose 的时间值
> 
> @davidelectricfree lastlogin 和 lastbrose 的时间值的问题修复了。更新docker镜像就行

好的，谢谢
